import React, { useState } from 'react';
import { FaGithub, FaCode } from 'react-icons/fa';

const Projects = () => {
  const [activeProject, setActiveProject] = useState(0);

  const projects = [
    {
      id: 1,
      title: 'Caption-Craft',
      subtitle: 'AI-Powered Video Captioning Platform',
      description: 'A comprehensive video captioning solution that leverages AWS services to automatically generate and edit captions for videos.',
      longDescription: 'Epique-Caps is a modern web application that simplifies video captioning through automation. Users can upload videos, and the platform automatically generates accurate captions using AWS Transcription services. The application features an intuitive editor for caption refinement and supports multiple video formats.',
      techStack: ['React', 'Next.js', 'Tailwind CSS', 'AWS S3', 'AWS Transcription'],
      features: [
        'User-friendly video upload interface',
        'Automatic caption generation using AWS Transcription',
        'Real-time caption editing and synchronization',
        'Secure video storage with AWS S3'
      ],
      image: '/project-placeholder.jpg',
      githubUrl: 'https://github.com/jeevithdharanish/Caption-Craft.git',
      status: 'Completed'
    },
    {
  id: 2,
  title: 'AI-View',
  subtitle: 'AI-Powered Interview Assistant',
  description: 'An interactive interview simulator that delivers real-time feedback using Vapi AI and Google Gemini.',
  longDescription: 'AI-View is a full-stack AI-powered interview assistant built with React, Next.js, and TypeScript. It uses Vapi AI to conduct real-time voice-based mock interviews and Google Gemini to generate intelligent, personalized feedback based on user responses. The platform helps users improve communication, confidence, and content through tailored analysis and coaching tips.',
  techStack: ['React', 'Next.js', 'TypeScript', 'Vapi AI', 'Google Gemini', 'Tailwind CSS'],
  features: [
    'Real-time voice-based mock interviews with Vapi AI',
    'Personalized interview feedback generated by Google Gemini',
    'Performance analysis based on tone, clarity, and content',
    'Type-safe code architecture using TypeScript'
  ],
  image: '/project-placeholder.jpg',
  githubUrl: 'https://github.com/jeevithdharanish/Ai-View.git',
  status: 'Completed'
}
,
    {
      id: 3,
      title: 'LinkMatrix',
      subtitle: 'Linktree Clone with Analytics',
      description: 'A Linktree alternative that provides detailed analytics and customization options for link management.',
      longDescription: 'LinkMatrix is a modern link-in-bio solution that goes beyond basic link sharing. It provides comprehensive analytics, custom themes, and advanced features for content creators and businesses to optimize their online presence.',
      techStack: ['React', 'Next.js', 'NextAuth', 'MongoDB', 'Tailwind CSS', 'AWS S3'],
      features: [
        'Custom link pages with themes',
        'Detailed click analytics and insights',
        'User authentication with NextAuth',
        'Social media integration',
        'Mobile-optimized interface'
      ],
      image: '/project-placeholder.jpg',
      githubUrl: 'https://github.com/jeevithdharanish/LinkMatrix.git',
      status: 'Completed'
    }
  ];

  const currentProject = projects[activeProject];

  return (
    <section id="projects" className="section-margin section-padding">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16 animate-fade-in">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Featured <span className="text-gradient">Projects</span>
          </h2>
          <p className="text-xl text-text-secondary max-w-2xl mx-auto">
            A showcase of my recent work and the technologies I&apos;ve used to build them
          </p>
        </div>

        {/* Project Navigation */}
        <div className="flex flex-wrap justify-center gap-4 mb-12">
          {projects.map((project, index) => (
            <button
              key={project.id}
              onClick={() => setActiveProject(index)}
              className={`px-6 py-3 rounded-lg font-medium transition-all duration-300 ${
                activeProject === index
                  ? 'bg-primary text-white shadow-lg'
                  : 'bg-surface-elevated hover:bg-surface border border-border text-text-secondary hover:text-text-primary'
              }`}
            >
              {project.title}
            </button>
          ))}
        </div>

        {/* Project Details */}
        <div className="max-w-4xl mx-auto">
          {/* Project Info */}
          <div className="space-y-6 animate-slide-up">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <h3 className="text-2xl md:text-3xl font-bold text-text-primary">
                  {currentProject.title}
                </h3>
                <span className="px-3 py-1 bg-primary/10 text-primary text-sm font-medium rounded-full">
                  {currentProject.status}
                </span>
              </div>
              <h4 className="text-lg text-text-secondary font-medium mb-4">
                {currentProject.subtitle}
              </h4>
              <p className="text-text-secondary leading-relaxed">
                {currentProject.longDescription}
              </p>
            </div>

            {/* Tech Stack */}
            <div>
              <h5 className="font-semibold text-text-primary mb-3">Tech Stack</h5>
              <div className="flex flex-wrap gap-2">
                {currentProject.techStack.map((tech, index) => (
                  <span
                    key={index}
                    className="px-3 py-1 bg-surface-elevated border border-border rounded-full text-sm text-text-secondary"
                  >
                    {tech}
                  </span>
                ))}
              </div>
            </div>

            {/* Features */}
            <div>
              <h5 className="font-semibold text-text-primary mb-3">Key Features</h5>
              <ul className="space-y-2">
                {currentProject.features.map((feature, index) => (
                  <li key={index} className="flex items-start gap-2 text-text-secondary">
                    <FaCode className="w-4 h-4 text-primary mt-1 flex-shrink-0" />
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Action Buttons */}
            <div className="flex justify-center pt-4">
              <a
                href={currentProject.githubUrl}
                className="btn btn-primary btn-md flex items-center gap-2"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaGithub className="w-4 h-4" />
                View Code
              </a>
            </div>
          </div>
        </div>
        {/* Divider Line */}
<div className="border-t border-border my-16 mx-auto w-2/3"></div>

      {/* View All Projects CTA */}
        <div className="text-center mt-16 animate-fade-in">
          <div className="card p-8 max-w-2xl mx-auto">
            <h3 className="text-xl font-semibold text-text-primary mb-4">
              Want to see more?
            </h3>
            <p className="text-text-secondary mb-6">
              Check out my GitHub profile for more projects and contributions to open source.
            </p>
            <a
              href="https://github.com/jdking123"
              target="_blank"
              rel="noopener noreferrer"
              className="btn btn-primary btn-md"
            >
              Visit My GitHub
            </a>
          </div>
        </div>

        
      </div>
      
    </section>
  );
};

export default Projects;
