// pages/index.js
import Header from "../components/Header";
import Head from "next/head";
import { useState } from "react";
import Introduction from '../components/Introduction';
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 transition-colors duration-300">
      <Header darkMode={darkMode} setDarkMode={setDarkMode}  />
      <Introduction/>
      {/* Other portfolio content here */}
      </main>
    </div>
  );
}
