import React from 'react';
import Layout from '../components/Layout';
import {
  FaJs,
  FaJava,
  FaReact,
  FaNodeJs,
  FaLinkedin,
  FaGithub,
  FaDownload,
  FaGraduationCap,
  FaCode,
  FaLightbulb,
  FaDatabase
} from 'react-icons/fa';
import {
  SiExpress,
  SiNextdotjs,
  SiGeeksforgeeks,
  SiMongodb,
  SiMysql
} from 'react-icons/si';
const Resume = () => {
  const skills = [
    { Icon: FaJs, label: 'JavaScript', color: 'text-yellow-500' },
    { Icon: FaJava, label: 'Java', color: 'text-red-500' },
    { Icon: FaReact, label: 'React', color: 'text-blue-400' },
    { Icon: FaNodeJs, label: 'Node.js', color: 'text-green-500' },
    { Icon: SiNextdotjs, label: 'Next.js', color: 'text-black dark:text-white' },
    { Icon: SiMongodb, label: 'MongoDB', color: 'text-green-600' },
    { Icon: SiExpress, label: 'Express.js', color: 'text-gray-600' },
    { Icon: FaDatabase, label: 'SQL', color: 'text-blue-600' }
  ];

  const projects = [
    {
      title: 'Epique-Caps',
      techStack: 'React, Tailwind CSS, AWS S3, AWS Transcription, Next.js',
      description: 'User-friendly video captioning platform with AWS integration for automatic caption generation and editing capabilities.',
      features: [
        'Automatic caption generation using AWS Transcription',
        'Secure video storage with AWS S3',
        'Real-time caption editing interface',
        'Multiple video format support'
      ]
    },
    {
      title: 'Ai-View',
      techStack: 'React,Tyescript,Firebase,Vapi ai',
     description: 'An interactive interview simulator that delivers real-time feedback using Vapi AI and Google Gemini.',
      features: [
        'Real-time voice-based mock interviews with Vapi AI',
    'Personalized interview feedback generated by Google Gemini',
    'Performance analysis based on tone, clarity, and content',
    'Type-safe code architecture using TypeScript'
      ]
    },
    {
      title: 'LinkMatrix',
      techStack: 'React, Tailwind CSS, Next.js, NextAuth, AWS S3, MongoDB',
      description: 'Linktree clone with advanced analytics for tracking link performance and user engagement.',
      features: [
        'Custom link pages with themes',
        'Detailed click analytics',
        'QR code generation',
        'Social media integration'
      ]
    }
  ];

  const personalLinks = [
    {
      icon: FaLinkedin,
      label: 'LinkedIn',
      url: 'https://www.linkedin.com/in/jeevithdharanish-m-01539328a/',
      text: 'Connect with me',
      color: 'text-blue-600'
    },
    {
      icon: FaGithub,
      label: 'GitHub',
      url: 'https://github.com/jdking123',
      text: 'View my repositories',
      color: 'text-black dark:text-gray-100'
    },
    {
      icon: SiGeeksforgeeks,
      label: 'GeeksforGeeks',
      url: 'https://www.geeksforgeeks.org/user/jeevithdhaa1s7/',
      text: 'Coding profile',
      color: 'text-green-600'
    },
    {
      icon: FaCode,
      label: 'Striver A2Z Sheet',
      url: 'https://takeuforward.org/profile/Jd_07',
      text: 'DSA progress',
      color: 'text-purple-600'
    }
  ];

  return (
    <Layout
      title="Resume - Jeevithdharanish"
      description="Professional resume of Jeevithdharanish showcasing skills, education, projects, and experience in software development."
    >
      <div className="min-h-screen section-padding py-16">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-16 animate-fade-in">
            {/* Breadcrumb */}
            <div className="flex items-center justify-center mb-6 text-sm">
              <span className="text-text-muted">Portfolio</span>
              <span className="mx-2 text-text-muted">/</span>
              <span className="text-primary font-medium">Resume</span>
            </div>

            <h1 className="text-4xl md:text-5xl font-bold mb-4">
              My <span className="text-gradient">Resume</span>
            </h1>
            <p className="text-xl text-text-secondary max-w-2xl mx-auto">
              A comprehensive overview of my skills, education, and professional journey
            </p>
          </div>

          {/* Skills Section */}
          <div className="mb-16 animate-slide-up">
            <div className="card p-8">
              <h2 className="text-2xl font-bold text-text-primary mb-6 flex items-center gap-3">
                <FaCode className="text-primary" />
                Technical Skills
              </h2>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-6">
                {skills.map(({ Icon, label, color }, idx) => (
                  <div key={idx} className="flex flex-col items-center p-4 rounded-lg bg-surface hover:bg-surface-elevated transition-colors">
                    <Icon className={`text-4xl mb-2 ${color}`} />
                    <span className="text-sm font-medium text-text-secondary text-center">{label}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Education & Personal Info */}
          <div className="grid md:grid-cols-2 gap-8 mb-16">
            {/* Education */}
            <div className="card p-8 animate-scale-in">
              <h2 className="text-2xl font-bold text-text-primary mb-6 flex items-center gap-3">
                <FaGraduationCap className="text-primary" />
                Education
              </h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold text-text-primary">
                    Master of Science in Software Systems
                  </h3>
                  <p className="text-text-secondary">Sri Krishna Arts and Science College (2021 - 2026)</p>
                  
                  <p className='text-sm'>CGPA -85%</p>
                </div>
              </div>
            </div>

            {/* Areas of Interest */}
            <div className="card p-8 animate-scale-in">
              <h2 className="text-2xl font-bold text-text-primary mb-6 flex items-center gap-3">
                <FaLightbulb className="text-primary" />
                Areas of Interest
              </h2>
              <ul className="space-y-3">
                {['Web Development', 'Cloud Technologies', 'Problem Solving', 'Software Architecture','Data Structures and Algorithms'].map((interest, idx) => (
                  <li key={idx} className="flex items-center gap-2 text-text-secondary">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    {interest}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Personal Links */}
          <div className="mb-16 animate-fade-in">
            <div className="card p-8">
              <h2 className="text-2xl font-bold text-text-primary mb-6">
                My Tech FootPrints
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {personalLinks.map(({ icon: Icon, label, url, text, color }, idx) => (
                  <a
                    key={idx}
                    href={url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center p-4 rounded-lg bg-surface hover:bg-surface-elevated border border-border transition-all duration-300 hover:scale-105"
                  >
                    <Icon className={`text-2xl mr-3 ${color}`} />
                    <div>
                      <div className="font-medium text-text-primary">{label}</div>
                      <div className="text-sm text-text-secondary">{text}</div>
                    </div>
                  </a>
                ))}
              </div>
            </div>
          </div>

          {/* Projects Section */}
          <div className="animate-slide-up">
            <div className="card p-8">
              <h2 className="text-2xl font-bold text-text-primary mb-6">
                Featured Projects
              </h2>
              <div className="space-y-8">
                {projects.map((project, idx) => (
                  <div key={idx} className="border-l-4 border-primary pl-6">
                    <h3 className="text-xl font-semibold text-text-primary mb-2">
                      {project.title}
                    </h3>
                    <p className="text-text-secondary mb-3">
                      {project.description}
                    </p>
                    <div className="mb-4">
                      <span className="text-sm font-medium text-text-primary">Tech Stack: </span>
                      <span className="text-sm text-text-secondary">{project.techStack}</span>
                    </div>
                    <ul className="space-y-1">
                      {project.features.map((feature, featureIdx) => (
                        <li key={featureIdx} className="flex items-start gap-2 text-sm text-text-secondary">
                          <div className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                          {feature}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Resume;
